# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 14:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_address', models.TextField(max_length=200)),
                ('product_description', models.TextField(blank=True, max_length=300)),
                ('product_price', models.FloatField()),
            ],
        ),
    ]
