# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 14:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0001_initial'),
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_truck',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.Truck'),
        ),
    ]
