# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 14:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentary',
            fields=[
                ('commentary_date', models.DateField(auto_created=True)),
                ('commentary_id', models.AutoField(primary_key=True, serialize=False)),
                ('commentary_text', models.TextField(max_length=300)),
                ('commentary_link', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id_post', models.AutoField(primary_key=True, serialize=False)),
                ('title_post', models.CharField(max_length=40)),
                ('text_post', models.TextField(max_length=512)),
                ('image1_post', models.CharField(blank=True, max_length=1000)),
                ('image2_post', models.CharField(blank=True, max_length=1000)),
                ('image3_post', models.CharField(blank=True, max_length=1000)),
                ('image4_post', models.CharField(blank=True, max_length=1000)),
                ('image5_post', models.CharField(blank=True, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Truck',
            fields=[
                ('truck_id', models.AutoField(primary_key=True, serialize=False)),
                ('truck_brend', models.CharField(max_length=48)),
                ('truck_model', models.CharField(max_length=48)),
                ('truck_release_year', models.IntegerField()),
                ('truck_type', models.CharField(max_length=48)),
                ('truck_mileage', models.IntegerField()),
                ('truck_gosnum', models.CharField(blank=True, max_length=15)),
                ('truck_vinnum', models.CharField(max_length=20)),
                ('truck_engine', models.CharField(max_length=48)),
                ('truck_engine_vol', models.FloatField()),
                ('truck_engine_power', models.FloatField()),
                ('truck_wheel_formula', models.CharField(max_length=3)),
                ('truck_image', models.CharField(blank=True, max_length=1000)),
                ('truck_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=64)),
                ('group_bool_moderator', models.BooleanField()),
                ('group_django', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='UserPersonal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(blank=True, max_length=24)),
                ('user_surname', models.CharField(blank=True, max_length=48)),
                ('user_gender', models.CharField(blank=True, max_length=1)),
                ('user_dateofbirth', models.DateField(null=True)),
                ('user_company_name', models.CharField(blank=True, max_length=128)),
                ('user_phone_number', models.CharField(blank=True, max_length=13)),
                ('user_image', models.CharField(blank=True, max_length=1000)),
                ('user_django', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.UserGroup')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False)),
                ('video_link', models.CharField(max_length=1000)),
                ('video_name', models.CharField(max_length=64)),
                ('video_description', models.TextField(blank=True, max_length=512)),
                ('video_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.UserPersonal')),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='author_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.UserPersonal'),
        ),
        migrations.AddField(
            model_name='commentary',
            name='commentary_author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='social.UserPersonal'),
        ),
    ]
