# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpersonal',
            name='user_dateofbirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
