# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-17 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_auto_20180117_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpersonal',
            name='id',
        ),
        migrations.AddField(
            model_name='userpersonal',
            name='user_id',
            field=models.AutoField(primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
